### ISSUE TITLE
Create form with validation

### ISSUE THREAD

**Issue by Neha** [Neha/javascript-projects#2]
- The form should check for following:
   - No input should be blank.
   - Email, number, name ,gender etc should be valid

**Comment by ashishmangla0** [comment]
I would like to work on it

**Comment by Neha** [comment]
@ashishmangla0  You can look into new solution :)

**Comment by fengkx** [comment]
Sorry. I don't know I should post a comment here before I start working on it. I didn't look at issue when post this pull request...
