### ISSUE TITLE
[costSplit] Add option to split by percentage

### ISSUE THREAD

**Issue by itaditya** [Neha/javascript-projects#6]
Currently we provide the total amount and number of people to distribute among and it distributes equally.

There should be a radio button which is an option to split by percentage. When user chooses that radio button, user will see four input boxes.

```
Name - Percentage
Name - Percentage
```
Once user clicks Calculate Percentage button we have to check that both the percentages add upto 100. If they do, show the amount to pay for each person.

```
Name - Percentage : Will pay Amount X
Name - Percentage : Will pay Amount Y
```

**Comment by itaditya** [comment]
Feel free to work on this issue. I'm opening this issue for Hacktoberfest participants

**Comment by alexxmitchell** [comment]
I would like to work on this
