### ISSUE TITLE
[wordCount] Twitter like textarea

### ISSUE THREAD

**Issue by itaditya** [Neha/javascript-projects#7]
In twitter when you write a tweet you can only write 280 characters. So this could be a project to have a textarea and below it something like `(20/280)`.

If the user enters more than 280 characters make the textarea border red.

**Comment by itaditya** [comment]
Opened this issue for Hacktoberfest participants. Feel free to pick it up

**Comment by insaurabh** [comment]
@Neha can I work on this if it's not done?

**Comment by insaurabh** [comment]
I think this is covered in #18 with basic functionality.

**Comment by sameershaik-tech** [comment]
can i work on this one?
